Sex form added
CrazyFlasher/domwires-as3 pull request #19
Opened 2018-05-14 13:50 UTC by lex2001

YO!

2018-05-14 14:04 UTC, lex2001 commented
чо за?

2018-05-15 08:50 UTC, CrazyFlasher commented
please, remove all redundant files added

2018-05-15 09:01 UTC, CrazyFlasher commented
please, fix code format in changed as files

2018-05-16 12:05 UTC, CrazyFlasher requested changes
Attach screenshot of final build

2018-05-16 12:05 UTC, CrazyFlasher commented on examples/simpleMVC/src/com/domwires/example/simplemvc/context/AppContext.as
> +            map(AppViewMessage.SEX_CLICKED, GenerateSexCommand);
improve code format

2018-05-16 12:05 UTC, CrazyFlasher commented on examples/simpleMVC/src/com/domwires/example/simplemvc/model/AppModel.as
> +        public function setSex(value:String):IAppModel
improve code format

2018-05-16 12:05 UTC, CrazyFlasher commented on examples/simpleMVC/src/com/domwires/example/simplemvc/model/AppModel.as
> +        public function get sex():String
improve code format

2018-05-16 12:05 UTC, CrazyFlasher commented on examples/simpleMVC/src/com/domwires/example/simplemvc/model/AppModelMessage.as
> +        public static const SEX_CHANGED:AppModelMessage = new AppModelMessage("SEX_CHANGED");
improve code format

2018-05-16 12:05 UTC, CrazyFlasher commented on examples/simpleMVC/src/com/domwires/example/simplemvc/model/IAppModel.as
> +        function setSex(value:String):IAppModel;
improve code format

2018-05-16 12:05 UTC, CrazyFlasher commented on examples/simpleMVC/src/com/domwires/example/simplemvc/model/IAppModelImmutable.as
> +        function get sex():String;
improve code format

2018-05-16 12:05 UTC, CrazyFlasher commented on examples/simpleMVC/src/com/domwires/example/simplemvc/view/AppView.as
> +        private var sexLabel:Label;
improve code format

2018-05-16 12:05 UTC, CrazyFlasher commented on examples/simpleMVC/src/com/domwires/example/simplemvc/view/AppView.as
> +            addMessageListener(AppModelMessage.SEX_CHANGED, sexNameChanged);
improve code format

2018-05-16 12:05 UTC, CrazyFlasher commented on examples/simpleMVC/src/com/domwires/example/simplemvc/view/AppView.as
> +        private function sexNameChanged(m:IMessage):void
improve code format

2018-05-16 12:05 UTC, CrazyFlasher commented on examples/simpleMVC/src/com/domwires/example/simplemvc/view/AppView.as
> +        private function onSexClicked():void
improve code format

2018-05-16 12:05 UTC, CrazyFlasher commented on examples/simpleMVC/src/com/domwires/example/simplemvc/view/AppViewMessage.as
> +        public static const SEX_CLICKED:AppViewMessage = new AppViewMessage("SEX_CLICKED");
improve code format

2018-06-12 04:54 UTC, closed without merging