fancy nickname generator # 2
CrazyFlasher/domwires-as3 pull request #22
Opened 2018-05-16 11:56 UTC by Chemoday

forgot to add file in previous one

2018-05-16 12:05 UTC, CrazyFlasher requested changes
Attach screenshot of final build

2018-05-16 12:05 UTC, CrazyFlasher commented on examples/simpleMVC/src/com/domwires/example/simplemvc/commands/GenerateNickNameCommand.as
> +		[Autowired]
improve code format

2018-05-16 12:05 UTC, CrazyFlasher commented on examples/simpleMVC/src/com/domwires/example/simplemvc/commands/GenerateNickNameCommand.as
> +            random_name = Math.floor(Math.random() * name.length);
do not use "_" in local variables. Example according language conventions: "randomName"

2018-05-16 12:05 UTC, CrazyFlasher commented on examples/simpleMVC/src/com/domwires/example/simplemvc/model/AppModel.as
> +        private var _nickName:String;
improve code format

2018-05-16 12:05 UTC, CrazyFlasher commented on examples/simpleMVC/src/com/domwires/example/simplemvc/model/AppModel.as
> +        public function setNickName(value:String):IAppModel
improve code format

2018-05-16 12:05 UTC, CrazyFlasher commented on examples/simpleMVC/src/com/domwires/example/simplemvc/model/AppModel.as
> +        public function get nickName():String
improve code format

2018-05-16 12:05 UTC, CrazyFlasher commented on examples/simpleMVC/src/com/domwires/example/simplemvc/view/AppView.as
> +            nickNameLabel = createForm("Nickname:", layoutGroup, onNickNameClicked);
improve code format

2018-05-16 12:05 UTC, CrazyFlasher commented on examples/simpleMVC/src/com/domwires/example/simplemvc/view/AppView.as
> +		private function nickNameChanged(m:IMessage):void
improve code format

2018-05-16 12:05 UTC, CrazyFlasher commented on examples/simpleMVC/src/com/domwires/example/simplemvc/view/AppView.as
> +		private function onNickNameClicked():void
improve code format

2018-05-16 12:23 UTC, Chemoday commented
project structure : http://joxi.ru/L210ovi65xJBmX
program : http://joxi.ru/ZrJXMNT1qlga2j

2018-05-24 06:48 UTC, CrazyFlasher commented
Please, resolve conflicts

2018-06-12 04:54 UTC, closed without merging